apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-process-movement
  labels:
    app: service-process-movement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-process-movement
  template:
    metadata:
      labels:
        app: service-process-movement
    spec:
      containers:
      - name: app-process-movement
        image: stivid007/nodejs-process-movement:5
        ports:
        - containerPort: 8080
        env:
        - name: NACOS_SERVERADDR
          value: "164.90.255.230:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-process-movement
spec:
  type: LoadBalancer
  selector:
    app: service-process-movement
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http